version: '3.8'

services:
    # PHP/Laravel Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: todo_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules  # This excludes the node_modules from being mounted
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - todo_network
        depends_on:
            - db

    # Nginx Service
    web:
        image: nginx:1.21
        container_name: todo_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - /var/www/node_modules  # This excludes the node_modules from being mounted
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - todo_network
        depends_on:
            - app

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: todo_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_PASSWORD: password
            MYSQL_USER: laravel_user
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        networks:
            - todo_network

    # Node Service for Vue.js
    node:
        image: node:16
        container_name: todo_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules  # This excludes the node_modules from being mounted
        networks:
            - todo_network
        # Modified to properly install dependencies in the container
        command: bash -c "rm -rf node_modules && npm install && npm run dev"

networks:
    todo_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
